### PR TITLE
Add support for autobpm plugin

### PR DESCRIPTION
**Pull request by tandy-1000**
I made a plugin that uses Librosa to calculate bpm automatically, it has been mainlined.
These dependencies are needed for it to work.

### CODE REVIEW

**Comment by sentriz** [comment]
thanks👌

**Comment by sentriz** [comment]
@tandy-1000 unfortunately it seems the librosa dependancy has made the CI build blow up to 6+ hours, which then gets killed from a timeout

i think it must be really slow to build numbas or skikit-learn or something on armv7. any ideas?

**Comment by tandy-1000** [comment]
Hmm, is anyone using armv7?

**Comment by tandy-1000** [comment]
Can we still build arm64 though? I'm using that :D

**Comment by sentriz** [comment]
hahaha oh dear

**Comment by tandy-1000** [comment]
also, I can't seem to access to containers at `ghcr.io/sentriz/betanin` is that the right link?

**Comment by sentriz** [comment]
looks like even building for arm64 is horrendously slow https://github.com/sentriz/betanin/actions/runs/6786467664

**Comment by sentriz** [comment]
@tandy-1000 approaching the 6 hour limit now. it looks like compiling for any architecture other than amd64 is a no go (at least with qemu on github actions)

any ideas? can we support bpm without numbas or whatever the package is?

**Comment by sentriz** [comment]
sorry really need to get a release out so i removed librosa for now. can we build it an alternative way that wont take ages? would be happy to accept a PR. there is a new "debug-release" github action so we can see how long a build would take for a PR

**Pull request merged**
